### ISSUE TITLE
Project: <short description>

### ISSUE THREAD

**Issue by jacobs1242** [microsoft/hack-together-dotnet#36] opened 2023-11-29 06:30 UTC
### Project name

CREATORS ARENA

### Description

The project “CREATORS ARENA” is a college based app used to identify the talents of the students . It will be very useful for students to show their extra curricular talents . Everyone in the college will be able to showcase their talents . With the help of this app, teachers can identify the one with talents and can boost up their confidence and to help them grow their talents. The main advantage of this app is that teachers can filter the content and select only the relevant ones. After filtering the contents , teachers will be able to approve it and everyone will be able to see it in the app. Students can make dubsmash,dance,songs,novel,story etc and post it. Creators arena mainly focuses on helping the students build their confidence and as a platform to show their talents. 

### Project Repository URL

https://github.com/jacobs1242/creators-arena

### Project video

https://drive.google.com/file/d/1_TquI8FXxgYeVzzDI94Xbe5Dzr-nuMBL/view?usp=drive_link

### Team members

JACOB,ASHIQMA

**Comment by codemillmatt** [comment] 2023-12-04 18:32
Duplicate of #37

**Closed by codemillmatt** 2023-12-04 18:32 UTC
Labels: duplicate, under review
